### ISSUE TITLE
firefox sometimes doesn't react to kill shortcut

### ISSUE THREAD

**Issue by ibabushkin** [ibabushkin/gabelstaplerwm#21]
# Roadmap
* [x] add logging of key callbacks.
* [x] analyze cause, possibly other issues:
  Apparentl firefox ignores our client message. We'll need to investigate further, why and how that happens.
* [ ] implement workaround / fix.

# Notes
It might be connected to firefox opening multiple windows (which we have trouble with), see #18.

**Comment by ibabushkin** [comment]
The issue is inherent to child windows of firefox not being closed, previously some went unnoticed.
